# Generated by Django 2.0.3 on 2018-06-21 00:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifeSwitchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='時間')),
                ('note', models.TextField(blank=True, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='LifeSwitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='種類')),
                ('is_on', models.BooleanField(default=False, verbose_name='オン・オフ')),
            ],
        ),
        migrations.CreateModel(
            name='TemporaryNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_note_by_type', to='multi_switch.LifeSwitchType', verbose_name='スイッチタイプ')),
            ],
        ),
        migrations.AddField(
            model_name='lifeswitchlog',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_by_type', to='multi_switch.LifeSwitchType', verbose_name='スイッチタイプ'),
        ),
    ]
